import type { Vendor } from "@/lib/purchase/types";

import { DEMO_BUSINESS } from "./business";
import { DEMO_ORG_ID, DEMO_WS_ID } from "./ids";

const stamped = "2026-01-05T06:00:00.000Z";

function vendor(
  partial: Omit<
    Vendor,
    "organizationId" | "workspaceId" | "status" | "createdAt" | "updatedAt"
  > &
    Partial<Pick<Vendor, "status">>,
): Vendor {
  return {
    organizationId: DEMO_ORG_ID,
    workspaceId: DEMO_WS_ID,
    status: "active",
    createdAt: stamped,
    updatedAt: stamped,
    ...partial,
  };
}

/**
 * ~15 realistic Indian vendors for StrideKids.
 * GSTIN prefix encodes state for interstate GST logic.
 */
export const DEMO_VENDORS: Vendor[] = [
  vendor({
    id: "vnd-nova-footwear",
    name: "Nova Footwear Industries",
    registrationType: "regular",
    businessCategory: "product_manufacturer",
    contactPerson: "Ramesh Pillai",
    gstin: "33AABCN8821F1Z2",
    pan: "AABCN8821F",
    phone: "+91 98410 22110",
    email: "sales@novafootwear.in",
    address: "Plot 48, SIPCOT Industrial Estate",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "602105",
    bankName: "HDFC Bank",
    bankAccountName: "Nova Footwear Industries",
    bankAccountNumber: "50200011223344",
    bankIfsc: "HDFC0001234",
    paymentTermsDays: 30,
    leadTimeDays: 14,
    rating: 4.6,
    notes: "Primary kids clog & sandal manufacturer",
    defaultPurchaseIntent: "sellable",
    allowedPurchaseIntents: ["sellable"],
  }),
  vendor({
    id: "vnd-agrasole",
    name: "AgraSole Traders",
    registrationType: "regular",
    businessCategory: "wholesaler",
    contactPerson: "Vikram Gupta",
    gstin: "09AAKFA4410Q1Z8",
    pan: "AAKFA4410Q",
    phone: "+91 98370 44120",
    email: "orders@agrasole.com",
    address: "14/2, Jeoni Mandi Footwear Market",
    city: "Agra",
    state: "Uttar Pradesh",
    pincode: "282003",
    bankName: "ICICI Bank",
    bankAccountName: "AgraSole Traders",
    bankAccountNumber: "62770100445566",
    bankIfsc: "ICIC0006277",
    paymentTermsDays: 45,
    leadTimeDays: 10,
    rating: 4.2,
    notes: "Women slippers & budget sandals wholesaler",
    defaultPurchaseIntent: "sellable",
    allowedPurchaseIntents: ["sellable"],
  }),
  vendor({
    id: "vnd-suratex",
    name: "SuratTex Hosiery LLP",
    registrationType: "regular",
    businessCategory: "product_manufacturer",
    contactPerson: "Mehul Shah",
    gstin: "24AAGFS2291C1Z5",
    pan: "AAGFS2291C",
    phone: "+91 98250 77881",
    email: "b2b@suratex.in",
    address: "Ring Road, Textile Market Shed B-12",
    city: "Surat",
    state: "Gujarat",
    pincode: "395002",
    bankName: "Axis Bank",
    bankAccountName: "SuratTex Hosiery LLP",
    bankAccountNumber: "91202004556677",
    bankIfsc: "UTIB0000123",
    paymentTermsDays: 21,
    leadTimeDays: 7,
    rating: 4.4,
    notes: "Socks & soft accessories",
    defaultPurchaseIntent: "sellable",
    allowedPurchaseIntents: ["sellable"],
  }),
  vendor({
    id: "vnd-raincraft",
    name: "RainCraft Polymers",
    registrationType: "regular",
    businessCategory: "product_manufacturer",
    contactPerson: "Sneha Kulkarni",
    gstin: "27AADCR6612H1Z9",
    pan: "AADCR6612H",
    phone: "+91 98200 33445",
    email: "accounts@raincraft.co.in",
    address: "MIDC Taloja, Plot W-19",
    city: "Navi Mumbai",
    state: "Maharashtra",
    pincode: "410208",
    bankName: "SBI",
    bankAccountName: "RainCraft Polymers",
    bankAccountNumber: "30123456789",
    bankIfsc: "SBIN0000456",
    paymentTermsDays: 15,
    leadTimeDays: 8,
    rating: 4.1,
    notes: "Rainwear & PVC accessories — MH intrastate",
    defaultPurchaseIntent: "consumable",
    allowedPurchaseIntents: ["consumable"],
  }),
  vendor({
    id: "vnd-packright",
    name: "PackRight Corrugators",
    registrationType: "regular",
    businessCategory: "packaging",
    contactPerson: "Anil Deshmukh",
    gstin: "27AABCP9910D1Z3",
    pan: "AABCP9910D",
    phone: "+91 97699 12001",
    email: "sales@packright.in",
    address: "Gala 7, Bhiwandi Anjurphata",
    city: "Bhiwandi",
    state: "Maharashtra",
    pincode: "421302",
    bankName: "Bank of Baroda",
    bankAccountName: "PackRight Corrugators",
    bankAccountNumber: "09820100012345",
    bankIfsc: "BARB0BHIWAN",
    paymentTermsDays: 15,
    leadTimeDays: 5,
    rating: 4.7,
    notes: "Mailer boxes & cartons near warehouse",
    defaultPurchaseIntent: "consumable",
    allowedPurchaseIntents: ["consumable"],
  }),
  vendor({
    id: "vnd-polywrap",
    name: "PolyWrap India",
    registrationType: "regular",
    businessCategory: "packaging",
    contactPerson: "Kavita Arora",
    gstin: "06AABCP4412E1Z6",
    pan: "AABCP4412E",
    phone: "+91 98110 55667",
    email: "orders@polywrap.in",
    address: "Sector 37, Udyog Vihar",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122001",
    bankName: "Kotak Mahindra Bank",
    bankAccountName: "PolyWrap India",
    bankAccountNumber: "8411478901",
    bankIfsc: "KKBK0000261",
    paymentTermsDays: 30,
    leadTimeDays: 6,
    rating: 4.0,
    notes: "Poly bags, void fill, tape",
    defaultPurchaseIntent: "consumable",
    allowedPurchaseIntents: ["consumable"],
  }),
  vendor({
    id: "vnd-labelmark",
    name: "LabelMark Stickers",
    registrationType: "composition",
    businessCategory: "labels",
    contactPerson: "Farhan Qureshi",
    gstin: "27AADFL2201P1ZB",
    pan: "AADFL2201P",
    phone: "+91 98920 77889",
    email: "hello@labelmark.in",
    address: "Shop 22, Dharavi Industrial Lane",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400017",
    bankName: "Yes Bank",
    bankAccountName: "LabelMark Stickers",
    bankAccountNumber: "013463700001234",
    bankIfsc: "YESB0000134",
    paymentTermsDays: 7,
    leadTimeDays: 3,
    rating: 3.9,
    notes: "Composition dealer — barcode & care labels",
    defaultPurchaseIntent: "consumable",
    allowedPurchaseIntents: ["consumable"],
  }),
  vendor({
    id: "vnd-shipfast",
    name: "ShipFast Logistics Pvt Ltd",
    registrationType: "regular",
    businessCategory: "courier",
    contactPerson: "Neha Iyer",
    gstin: "27AAGCS7712K1Z4",
    pan: "AAGCS7712K",
    phone: "+91 22 4890 1200",
    email: "billing@shipfast.in",
    address: "Andheri East, MIDC Cross Road B",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400093",
    bankName: "HDFC Bank",
    bankAccountName: "ShipFast Logistics Pvt Ltd",
    bankAccountNumber: "50200099887766",
    bankIfsc: "HDFC0000240",
    paymentTermsDays: 0,
    leadTimeDays: 0,
    rating: 4.3,
    notes: "Courier wallet recharges — prepaid",
    defaultPurchaseIntent: "freight",
    allowedPurchaseIntents: ["freight"],
  }),
  vendor({
    id: "vnd-officemart",
    name: "OfficeMart Wholesale",
    registrationType: "regular",
    businessCategory: "office_supplies",
    contactPerson: "Priya Nair",
    gstin: "27AABCO3310M1Z7",
    pan: "AABCO3310M",
    phone: "+91 98209 33440",
    email: "b2b@officemart.co.in",
    address: "Lamington Road, Grant Road West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400007",
    bankName: "Union Bank",
    bankAccountName: "OfficeMart Wholesale",
    bankAccountNumber: "510101234567890",
    bankIfsc: "UBIN0533441",
    paymentTermsDays: 15,
    leadTimeDays: 2,
    rating: 4.0,
    defaultPurchaseIntent: "consumable",
    allowedPurchaseIntents: ["consumable"],
  }),
  vendor({
    id: "vnd-meta-ads",
    name: "PixelReach Media",
    registrationType: "regular",
    businessCategory: "marketing",
    contactPerson: "Arjun Mehta",
    gstin: "07AABCP8821L1Z1",
    pan: "AABCP8821L",
    phone: "+91 98100 22334",
    email: "invoices@pixelreach.in",
    address: "Okhla Phase II, Workspace 4B",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110020",
    bankName: "ICICI Bank",
    bankAccountName: "PixelReach Media",
    bankAccountNumber: "004401012345",
    bankIfsc: "ICIC0000044",
    paymentTermsDays: 7,
    leadTimeDays: 0,
    rating: 4.5,
    notes: "Meta / Facebook ads retainer + media",
    defaultPurchaseIntent: "marketing",
    allowedPurchaseIntents: ["marketing"],
  }),
  vendor({
    id: "vnd-searchads",
    name: "ClickNorth Digital",
    registrationType: "regular",
    businessCategory: "marketing",
    contactPerson: "Sanya Kapoor",
    gstin: "29AABCC6612R1Z0",
    pan: "AABCC6612R",
    phone: "+91 80 4123 8890",
    email: "finance@clicknorth.in",
    address: "Koramangala 5th Block",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560095",
    bankName: "Axis Bank",
    bankAccountName: "ClickNorth Digital",
    bankAccountNumber: "922010012345678",
    bankIfsc: "UTIB0000129",
    paymentTermsDays: 15,
    leadTimeDays: 0,
    rating: 4.2,
    notes: "Google Ads managed spend",
    defaultPurchaseIntent: "marketing",
    allowedPurchaseIntents: ["marketing"],
  }),
  vendor({
    id: "vnd-billbooks",
    name: "Ledgerly SaaS India",
    registrationType: "regular",
    businessCategory: "software",
    contactPerson: "Support Billing",
    gstin: "29AAGCL4410T1Z8",
    pan: "AAGCL4410T",
    phone: "+91 80 8899 1200",
    email: "billing@ledgerly.in",
    address: "Manyata Tech Park, Nagawara",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560045",
    bankName: "HDFC Bank",
    bankAccountName: "Ledgerly SaaS India",
    bankAccountNumber: "50200055667788",
    bankIfsc: "HDFC0000555",
    paymentTermsDays: 0,
    leadTimeDays: 0,
    rating: 4.8,
    notes: "Accounting + invoicing subscription",
    defaultPurchaseIntent: "service",
    allowedPurchaseIntents: ["service"],
  }),
  vendor({
    id: "vnd-ca-firm",
    name: "Sharma & Associates Chartered Accountants",
    registrationType: "regular",
    businessCategory: "professional_service",
    contactPerson: "CA Deepak Sharma",
    gstin: "27AABFS2299Q1Z2",
    pan: "AABFS2299Q",
    phone: "+91 22 2678 4410",
    email: "deepak@sharmaassociates.in",
    address: "Borivali West, SV Road",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400092",
    bankName: "SBI",
    bankAccountName: "Sharma and Associates",
    bankAccountNumber: "38920123456",
    bankIfsc: "SBIN0003892",
    paymentTermsDays: 15,
    leadTimeDays: 0,
    rating: 4.9,
    notes: "GST filing & compliance",
    defaultPurchaseIntent: "service",
    allowedPurchaseIntents: ["service"],
  }),
  vendor({
    id: "vnd-msedcl",
    name: "MSEDCL Commercial",
    registrationType: "tax_deductor_collector",
    businessCategory: "utilities",
    contactPerson: "Commercial Desk",
    gstin: "27AAACM1234F1Z0",
    pan: "AAACM1234F",
    phone: "+91 1912",
    email: "commercial@mahadiscom.in",
    address: "Bhiwandi Circle Office",
    city: "Bhiwandi",
    state: "Maharashtra",
    pincode: "421302",
    bankName: "SBI",
    bankAccountName: "MSEDCL",
    bankAccountNumber: "111122223333",
    bankIfsc: "SBIN0000456",
    paymentTermsDays: 0,
    leadTimeDays: 0,
    rating: 3.5,
    notes: "Warehouse electricity",
    defaultPurchaseIntent: "expense",
    allowedPurchaseIntents: ["expense"],
  }),
  vendor({
    id: "vnd-airlink",
    name: "AirLink Broadband",
    registrationType: "regular",
    businessCategory: "utilities",
    contactPerson: "Enterprise Care",
    gstin: "27AABCA7788N1Z5",
    pan: "AABCA7788N",
    phone: "+91 1800 209 9898",
    email: "enterprise@airlink.in",
    address: "Thane West Enterprise Hub",
    city: "Thane",
    state: "Maharashtra",
    pincode: "400601",
    bankName: "ICICI Bank",
    bankAccountName: "AirLink Broadband",
    bankAccountNumber: "000401234567",
    bankIfsc: "ICIC0000004",
    paymentTermsDays: 0,
    leadTimeDays: 0,
    rating: 3.8,
    defaultPurchaseIntent: "service",
    allowedPurchaseIntents: ["service"],
  }),
  vendor({
    id: "vnd-steelrack",
    name: "SteelCart Warehouse Systems",
    registrationType: "regular",
    businessCategory: "assets",
    contactPerson: "Harish Patil",
    gstin: "27AAGCS5521W1Z6",
    pan: "AAGCS5521W",
    phone: "+91 97654 11220",
    email: "sales@steelcart.in",
    address: "Wagle Estate, Road No. 16",
    city: "Thane",
    state: "Maharashtra",
    pincode: "400604",
    bankName: "Bank of Maharashtra",
    bankAccountName: "SteelCart Warehouse Systems",
    bankAccountNumber: "60123456789",
    bankIfsc: "MAHB0000123",
    paymentTermsDays: 30,
    leadTimeDays: 12,
    rating: 4.1,
    notes: "Racks, printers, warehouse assets",
    defaultPurchaseIntent: "asset",
    allowedPurchaseIntents: ["asset"],
  }),
  vendor({
    id: "vnd-landlord",
    name: "Patil Industrial Properties",
    registrationType: "unregistered",
    businessCategory: "other",
    contactPerson: "Suresh Patil",
    pan: "AABPP4412L",
    phone: "+91 98211 55660",
    email: "rent@patilproperties.in",
    address: "Bhiwandi Anjurphata Road",
    city: "Bhiwandi",
    state: "Maharashtra",
    pincode: "421302",
    bankName: "HDFC Bank",
    bankAccountName: "Suresh Patil",
    bankAccountNumber: "50100233445566",
    bankIfsc: "HDFC0001789",
    paymentTermsDays: 0,
    leadTimeDays: 0,
    rating: 4.0,
    notes: `Warehouse rent for ${DEMO_BUSINESS.brand} — unregistered landlord`,
    defaultPurchaseIntent: "expense",
    allowedPurchaseIntents: ["expense"],
  }),
];

export function vendorById(id: string): Vendor | null {
  const found = DEMO_VENDORS.find((row) => row.id === id);
  return found ?? null;
}
