"use client";

import { useEffect, useState } from "react";
import {
  AlertTriangle,
  ArrowRight,
  Brain,
  CheckCircle2,
  Clock,
  Coins,
  Copy,
  Download,
  FileText,
  Layers,
  Share2,
  Sparkles,
  Trash2,
  TrendingUp,
  X,
} from "lucide-react";
import { aiReportEngine, type AiExecutiveReport } from "@/lib/core/ai-report-engine";

interface AiExecutiveReportModalProps {
  report: AiExecutiveReport | null;
  isOpen: boolean;
  onClose: () => void;
}

export default function AiExecutiveReportModal({
  report,
  isOpen,
  onClose,
}: AiExecutiveReportModalProps) {
  const [copiedId, setCopiedId] = useState(false);
  const [toastMsg, setToastMsg] = useState<string | null>(null);

  // ESC to close
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isOpen) onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [isOpen, onClose]);

  if (!isOpen || !report) return null;

  const handleCopyId = () => {
    navigator.clipboard.writeText(report.id);
    setCopiedId(true);
    setTimeout(() => setCopiedId(false), 2000);
  };

  const handleDuplicate = () => {
    const newRep = aiReportEngine.duplicateReport(report.id);
    if (newRep) {
      setToastMsg(`Duplicated as ${newRep.id}`);
      setTimeout(() => setToastMsg(null), 3000);
    }
  };

  const handleDelete = () => {
    if (confirm(`Delete Report ${report.id}?`)) {
      aiReportEngine.deleteReport(report.id);
      onClose();
    }
  };

  const handleExportPdf = () => {
    setToastMsg(`Report ${report.id} exported to PDF`);
    setTimeout(() => setToastMsg(null), 3000);
  };

  const handleApplyRec = (recId: string) => {
    aiReportEngine.toggleApplyRecommendation(report.id, recId);
  };

  return (
    <div className="fixed inset-0 z-[170] flex items-center justify-center bg-slate-950/70 backdrop-blur-xs p-4 animate-in fade-in duration-200 overflow-y-auto">
      <div className="relative w-full max-w-4xl my-8 overflow-hidden rounded-2xl bg-white shadow-2xl border border-slate-200 text-slate-800">
        
        {/* Toast Notification */}
        {toastMsg && (
          <div className="absolute top-4 right-16 z-50 px-3 py-1.5 bg-slate-900 text-white rounded-lg text-xs font-bold shadow-lg animate-in fade-in">
            ✓ {toastMsg}
          </div>
        )}

        {/* Executive Report Header Bar */}
        <div className="px-6 py-5 border-b border-slate-100 bg-gradient-to-r from-slate-900 via-slate-900 to-indigo-950 text-white flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 flex-wrap mb-1">
              <span className="text-[10px] font-black px-2.5 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 uppercase tracking-wider font-mono">
                {report.module.toUpperCase()} EXECUTIVE REPORT
              </span>
              <span className="text-[10px] font-mono text-slate-400">
                ID: <button type="button" onClick={handleCopyId} className="hover:text-amber-300 font-bold underline cursor-pointer">{report.id}</button>
                {copiedId && " (Copied!)"}
              </span>
            </div>
            <h2 className="text-xl md:text-2xl font-black text-white">{report.title}</h2>
            <p className="text-xs text-indigo-300 mt-1">Generated by {report.user} • {new Date(report.generatedAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</p>
          </div>

          <div className="flex items-center gap-3">
            {/* Health Score Gauge Circle */}
            <div className="text-center">
              <div className="relative w-14 h-14">
                <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                  <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="#1e293b" strokeWidth="3" />
                  <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke={report.healthScore >= 70 ? "#10b981" : "#f59e0b"} strokeWidth="3" strokeLinecap="round" strokeDasharray={`${report.healthScore}, 100`} />
                </svg>
                <span className="absolute inset-0 flex items-center justify-center text-sm font-black text-white">{report.healthScore}</span>
              </div>
              <p className="text-[9px] font-bold text-slate-400 mt-0.5">Health Score</p>
            </div>

            <button type="button" onClick={onClose} className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Metadata Toolbar */}
        <div className="px-6 py-2.5 bg-slate-50 border-b border-slate-200 flex flex-wrap items-center justify-between text-xs font-mono text-slate-600 gap-3">
          <div className="flex items-center gap-4">
            <span>Credits Used: <strong className="text-indigo-700 font-extrabold">{report.creditsUsed}</strong></span>
            <span>Runtime: <strong className="text-slate-800 font-extrabold">{(report.executionDurationMs / 1000).toFixed(1)}s</strong></span>
            <span>Status: <strong className="text-emerald-700 font-extrabold uppercase">✓ {report.lifecycleState}</strong></span>
          </div>

          <div className="flex items-center gap-2">
            <button type="button" onClick={handleExportPdf} className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 text-slate-700 font-bold rounded-lg text-[10px] transition flex items-center gap-1 cursor-pointer">
              <Download className="w-3 h-3" /> Export PDF
            </button>
            <button type="button" onClick={handleDuplicate} className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 text-slate-700 font-bold rounded-lg text-[10px] transition flex items-center gap-1 cursor-pointer">
              <Copy className="w-3 h-3" /> Duplicate
            </button>
            <button type="button" onClick={handleDelete} className="px-2.5 py-1 bg-rose-50 hover:bg-rose-100 border border-rose-200 text-rose-700 font-bold rounded-lg text-[10px] transition flex items-center gap-1 cursor-pointer">
              <Trash2 className="w-3 h-3" /> Delete
            </button>
          </div>
        </div>

        {/* Report Body */}
        <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto">

          {/* 1. Financial Impact Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-xl bg-emerald-50 border border-emerald-200">
              <p className="text-[10px] font-extrabold uppercase tracking-wider text-emerald-800">Estimated Monthly Savings</p>
              <p className="text-xl font-black text-emerald-700 mt-0.5">₹{report.estimatedSavingsInr.toLocaleString()}</p>
            </div>
            <div className="p-3.5 rounded-xl bg-indigo-50 border border-indigo-200">
              <p className="text-[10px] font-extrabold uppercase tracking-wider text-indigo-800">Revenue Protected</p>
              <p className="text-xl font-black text-indigo-700 mt-0.5">₹{(report.revenueProtectedInr / 100000).toFixed(1)}L</p>
            </div>
            <div className="p-3.5 rounded-xl bg-amber-50 border border-amber-200">
              <p className="text-[10px] font-extrabold uppercase tracking-wider text-amber-900">Working Capital Recoverable</p>
              <p className="text-xl font-black text-amber-800 mt-0.5">₹{(report.workingCapitalReleasedInr / 1000).toFixed(0)}K</p>
            </div>
            <div className="p-3.5 rounded-xl bg-violet-50 border border-violet-200">
              <p className="text-[10px] font-extrabold uppercase tracking-wider text-violet-800">Expected ROI</p>
              <p className="text-xl font-black text-violet-700 mt-0.5">{report.expectedRoi}</p>
            </div>
          </div>

          {/* 2. Executive Summary */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1.5">
            <h3 className="text-xs font-black uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5 text-indigo-600" /> Executive Summary
            </h3>
            <p className="text-xs text-slate-800 leading-relaxed font-medium">
              {report.executiveSummary}
            </p>
          </div>

          {/* 3. Key Findings */}
          <div>
            <h3 className="text-xs font-black uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-500" /> Key Intelligence Findings ({report.keyFindings.length})
            </h3>
            <div className="space-y-2">
              {report.keyFindings.map((finding) => (
                <div key={finding.id} className="p-3.5 rounded-xl border border-slate-200 bg-white shadow-2xs space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-slate-900">{finding.title}</span>
                    <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full uppercase ${
                      finding.severity === "critical" ? "bg-rose-100 text-rose-800 border border-rose-300" :
                      finding.severity === "warning" ? "bg-amber-100 text-amber-800 border border-amber-300" :
                      "bg-emerald-100 text-emerald-800 border border-emerald-300"
                    }`}>
                      {finding.severity}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 leading-snug">{finding.detail}</p>
                </div>
              ))}
            </div>
          </div>

          {/* 4. Actionable Recommendations */}
          <div>
            <h3 className="text-xs font-black uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-1.5">
              <TrendingUp className="w-3.5 h-3.5 text-emerald-600" /> Actionable Recommendations ({report.recommendations.length})
            </h3>
            <div className="space-y-2.5">
              {report.recommendations.map((rec) => (
                <div key={rec.id} className="p-4 rounded-xl border border-slate-200 bg-white shadow-2xs flex flex-wrap items-center justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-black text-slate-900">{rec.title}</p>
                    <p className="text-xs text-slate-600 mt-0.5">{rec.action}</p>
                    <span className="inline-block text-[10px] font-mono font-bold text-emerald-700 mt-1">
                      Est. Business Impact: +₹{rec.impactInr.toLocaleString()}
                    </span>
                  </div>

                  <button
                    type="button"
                    onClick={() => handleApplyRec(rec.id)}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1 cursor-pointer shrink-0 ${
                      rec.isApplied
                        ? "bg-emerald-100 text-emerald-800 border border-emerald-300"
                        : "bg-indigo-600 text-white hover:bg-indigo-500 shadow-2xs"
                    }`}
                  >
                    {rec.isApplied ? (
                      <>
                        <CheckCircle2 className="w-3.5 h-3.5" /> Action Applied
                      </>
                    ) : (
                      <>
                        Apply Action <ArrowRight className="w-3 h-3" />
                      </>
                    )}
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* 5. Report Audit & Data Sources Trace */}
          <div className="p-4 rounded-xl bg-slate-900 text-white space-y-2 text-xs">
            <h4 className="font-extrabold text-indigo-300 flex items-center gap-1.5">
              <Layers className="w-3.5 h-3.5 text-amber-400" /> Data Sources & Audit Trace
            </h4>
            <div className="flex flex-wrap gap-2">
              {report.dataSources.map((ds) => (
                <span key={ds} className="text-[10px] font-mono px-2 py-1 rounded bg-slate-800 text-slate-300 border border-slate-700">
                  ✓ {ds}
                </span>
              ))}
            </div>
            {report.appliedActions.length > 0 && (
              <div className="pt-2 border-t border-slate-800">
                <p className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider">Applied Actions History:</p>
                <ul className="list-disc list-inside text-xs text-slate-300 mt-0.5 space-y-0.5">
                  {report.appliedActions.map((act, i) => (
                    <li key={i}>{act}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>

        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
          <span className="text-xs font-mono text-slate-500">CommerceOS Executive AI Report System SOT</span>
          <button type="button" onClick={onClose} className="px-4 py-2 bg-slate-900 text-white font-bold rounded-xl text-xs hover:bg-slate-800 transition cursor-pointer">
            Close Report
          </button>
        </div>

      </div>
    </div>
  );
}
