import type { UniversalAttribute } from "./types";

export const STANDARD_UNIVERSAL_ATTRIBUTES: UniversalAttribute[] = [
  {
    key: "color",
    label: "Primary Color",
    dataType: "string",
    allowedValues: [
      "Black",
      "White",
      "Blue",
      "Red",
      "Pink",
      "Green",
      "Yellow",
      "Orange",
      "Purple",
      "Brown",
      "Grey",
      "Beige",
      "Gold",
      "Silver",
      "Multicolor",
    ],
    group: "general",
    description: "The primary base color of the product.",
    active: true,
  },
  {
    key: "size",
    label: "Size",
    dataType: "string",
    allowedValues: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "Free Size"],
    group: "variant",
    description: "Standard apparel or universal sizing value.",
    active: true,
  },
  {
    key: "shoe_size_uk",
    label: "Shoe Size (UK/India)",
    dataType: "number",
    allowedValues: ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    group: "variant",
    description: "Footwear sizing for India/UK standard scale.",
    active: true,
  },
  {
    key: "gender",
    label: "Gender / Target Audience",
    dataType: "enum",
    allowedValues: ["Men", "Women", "Boys", "Girls", "Unisex Kids", "Unisex Adults"],
    group: "general",
    description: "Target demographic for catalog search categorization.",
    active: true,
  },
  {
    key: "age_group",
    label: "Age Group",
    dataType: "enum",
    allowedValues: ["Infant (0-12m)", "Toddler (1-3y)", "Kids (4-12y)", "Teens", "Adults"],
    group: "general",
    description: "Age classification of the intended consumer.",
    active: true,
  },
  {
    key: "material",
    label: "Primary Material",
    dataType: "string",
    allowedValues: [
      "Cotton",
      "Leather",
      "Synthetic Leather",
      "Polyester",
      "Rubber",
      "EVA",
      "Silk",
      "Denim",
      "Linen",
      "Canvas",
      "Mesh",
    ],
    group: "physical",
    description: "Main material used in construction.",
    active: true,
  },
  {
    key: "closure_type",
    label: "Closure Type",
    dataType: "enum",
    allowedValues: ["Hook and Loop", "Buckle", "Lace-Up", "Slip-On", "Zipper", "Button"],
    group: "general",
    description: "Closure or fastening mechanism.",
    active: true,
  },
  {
    key: "country_of_origin",
    label: "Country of Origin",
    dataType: "string",
    allowedValues: ["India", "Vietnam", "Bangladesh", "China", "Sri Lanka", "Indonesia"],
    group: "compliance",
    description: "Mandatory regulatory country of manufacture.",
    active: true,
  },
  {
    key: "care_instructions",
    label: "Care Instructions",
    dataType: "string",
    group: "compliance",
    description: "Washing, cleaning, and maintenance guidance.",
    active: true,
  },
  {
    key: "warranty_period",
    label: "Warranty Period",
    dataType: "string",
    allowedValues: ["No Warranty", "1 Month", "3 Months", "6 Months", "1 Year", "2 Years"],
    group: "compliance",
    description: "Manufacturer or seller warranty duration.",
    active: true,
  },
];

export function getUniversalAttribute(key: string): UniversalAttribute | undefined {
  return STANDARD_UNIVERSAL_ATTRIBUTES.find((attr) => attr.key === key);
}

export function getAllUniversalAttributes(): UniversalAttribute[] {
  return STANDARD_UNIVERSAL_ATTRIBUTES;
}
