import type { MarketplaceName } from "@/lib/types/master-listing";
import type { MarketplaceRegistryDefinition } from "./types";

export const SUPPORTED_MARKETPLACES: Record<string, MarketplaceRegistryDefinition> = {
  AMAZON: {
    code: "AMAZON" as MarketplaceName,
    name: "Amazon India",
    countryCode: "IN",
    category: "MARKETPLACE",
    documentationUrl: "https://developer-docs.amazon.com/sp-api/",
    capabilities: [
      "CATALOG_PUBLISH",
      "CATALOG_UPDATE",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "BUY_BOX_MONITORING",
      "ORDER_FULFILLMENT",
      "RETURN_MANAGEMENT",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["IN", "AE", "SA", "US", "UK"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  FLIPKART: {
    code: "FLIPKART" as MarketplaceName,
    name: "Flipkart",
    countryCode: "IN",
    category: "MARKETPLACE",
    documentationUrl: "https://seller.flipkart.com/api-docs",
    capabilities: [
      "CATALOG_PUBLISH",
      "CATALOG_UPDATE",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
      "RETURN_MANAGEMENT",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  MEESHO: {
    code: "MEESHO" as MarketplaceName,
    name: "Meesho",
    countryCode: "IN",
    category: "MARKETPLACE",
    documentationUrl: "https://supplier.meesho.com/api",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
      "RETURN_MANAGEMENT",
    ],
    authType: "TOKEN_SECRET",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: false,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  MYNTRA: {
    code: "MYNTRA" as MarketplaceName,
    name: "Myntra",
    countryCode: "IN",
    category: "MARKETPLACE",
    documentationUrl: "https://partners.myntra.com/api",
    capabilities: [
      "CATALOG_PUBLISH",
      "CATALOG_UPDATE",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  AJIO: {
    code: "AJIO" as MarketplaceName,
    name: "AJIO",
    countryCode: "IN",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  NYKAA: {
    code: "NYKAA" as MarketplaceName,
    name: "Nykaa Fashion",
    countryCode: "IN",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  TATACLIQ: {
    code: "TATACLIQ" as MarketplaceName,
    name: "Tata CLiQ",
    countryCode: "IN",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  SNAPDEAL: {
    code: "SNAPDEAL" as MarketplaceName,
    name: "Snapdeal",
    countryCode: "IN",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: false,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  JIOMART: {
    code: "JIOMART" as MarketplaceName,
    name: "JioMart",
    countryCode: "IN",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  SHOPSY: {
    code: "SHOPSY" as MarketplaceName,
    name: "Shopsy by Flipkart",
    countryCode: "IN",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: false,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  SHOPIFY: {
    code: "SHOPIFY" as MarketplaceName,
    name: "Shopify Store",
    countryCode: "GLOBAL",
    category: "STORE",
    documentationUrl: "https://shopify.dev/docs/api/admin-graphql",
    capabilities: [
      "CATALOG_PUBLISH",
      "CATALOG_UPDATE",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
      "IMAGE_HOSTING",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["GLOBAL"],
    requiresSellerId: false,
    requiresBrandApproval: false,
    requiresGstCompliance: false,
  },
  WOOCOMMERCE: {
    code: "WOOCOMMERCE" as MarketplaceName,
    name: "WooCommerce",
    countryCode: "GLOBAL",
    category: "STORE",
    documentationUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    capabilities: [
      "CATALOG_PUBLISH",
      "CATALOG_UPDATE",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["GLOBAL"],
    requiresSellerId: false,
    requiresBrandApproval: false,
    requiresGstCompliance: false,
  },
  EBAY: {
    code: "EBAY" as MarketplaceName,
    name: "eBay",
    countryCode: "US",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["US", "UK", "DE", "AU"],
    requiresSellerId: true,
    requiresBrandApproval: false,
    requiresGstCompliance: false,
  },
  ETSY: {
    code: "ETSY" as MarketplaceName,
    name: "Etsy",
    countryCode: "US",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["GLOBAL"],
    requiresSellerId: true,
    requiresBrandApproval: false,
    requiresGstCompliance: false,
  },
  WALMART: {
    code: "WALMART" as MarketplaceName,
    name: "Walmart Marketplace",
    countryCode: "US",
    category: "MARKETPLACE",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "BUY_BOX_MONITORING",
    ],
    authType: "OAUTH2",
    active: true,
    supportedRegions: ["US", "CA", "MX"],
    requiresSellerId: true,
    requiresBrandApproval: true,
    requiresGstCompliance: false,
  },
  ONDC: {
    code: "ONDC" as MarketplaceName,
    name: "ONDC (Open Network for Digital Commerce)",
    countryCode: "IN",
    category: "NETWORK",
    documentationUrl: "https://ondc.org/developer-guide",
    capabilities: [
      "CATALOG_PUBLISH",
      "PRICE_SYNC",
      "INVENTORY_SYNC",
      "ORDER_SYNC",
      "ORDER_FULFILLMENT",
    ],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["IN"],
    requiresSellerId: true,
    requiresBrandApproval: false,
    requiresGstCompliance: true,
    defaultTaxRate: 18,
  },
  GENERIC: {
    code: "GENERIC" as MarketplaceName,
    name: "Generic Channel",
    countryCode: "GLOBAL",
    category: "MARKETPLACE",
    capabilities: ["CATALOG_PUBLISH", "PRICE_SYNC", "INVENTORY_SYNC"],
    authType: "API_KEY",
    active: true,
    supportedRegions: ["GLOBAL"],
    requiresSellerId: false,
    requiresBrandApproval: false,
    requiresGstCompliance: false,
  },
};

export function getMarketplaceRegistry(code: MarketplaceName | string): MarketplaceRegistryDefinition {
  const key = String(code).toUpperCase();
  return SUPPORTED_MARKETPLACES[key] || SUPPORTED_MARKETPLACES.GENERIC;
}

export function getAllMarketplaceRegistries(): MarketplaceRegistryDefinition[] {
  return Object.values(SUPPORTED_MARKETPLACES);
}
